fail ah intentionally

diff --git a/.github/workflows/release_ah.yml b/.github/workflows/release_ah.yml
--- a/.github/workflows/release_ah.yml
+++ b/.github/workflows/release_ah.yml
@@ -30,7 +30,7 @@ jobs:
         run: |
           echo "${{ secrets.ah_token != '' }}"
           echo "${{ secrets.ansible_galaxy_api_key != '' }}"
-          [[ "${{ secrets.ah_token != '' }}" ]] || { echo "ah_token is required to publish on automation hub" ; exit 0; }
+          [[ "${{ secrets.ah_token_mod != '' }}" ]] || { echo "ah_token is required to publish on automation hub" ; exit 1; }
         # [[ "${{ secrets.ah_token != '' }}" ]] || { echo "ah_token is required to publish on automation hub" ; exit 1; }
         # TARBALL=$(ls -1 ./*.tar.gz)
         # cat << EOF > ansible.cfg
