formatter update

diff --git a/.github/workflows/release_ah.yaml b/.github/workflows/release_ah.yaml
--- a/.github/workflows/release_ah.yaml
+++ b/.github/workflows/release_ah.yaml
@@ -1,6 +1,6 @@
 ---
-name: "Automation Hub release"
-on:
+name: Automation Hub release
+"on":
   workflow_call:
     inputs:
       ah_publish:
@@ -14,31 +14,40 @@ on:
     secrets:
       ah_token:
         required: false
-
 jobs:
   release:
     runs-on: ubuntu-latest
     name: Automation Hub release
-    environment: ${{ inputs.environment }}
+    environment: "${{ inputs.environment }}"
     steps:
       - uses: actions/checkout@v4
-
-      - name: "Build the collection"
+      - name: Build the collection
         run: |
           ansible-galaxy collection build -v --force
+      - name: Publish the collection on Automation Hub
+        if: "${{ inputs.ah_publish }}"
+        run: >
+          [[ "${{ secrets.ah_token != '' }}" ]] || { echo "ah_token is required
+          to publish on automation hub" ; exit 1; }
 
-      - name: "Publish the collection on Automation Hub"
-        if: ${{ inputs.ah_publish }}
-        run: |
-          [[ "${{ secrets.ah_token != '' }}" ]] || { echo "ah_token is required to publish on automation hub" ; exit 1; }
           TARBALL=$(ls -1 ./*.tar.gz)
+
           cat << EOF > ansible.cfg
+
           [galaxy]
+
           server_list = rh_automation_hub
+
           [galaxy_server.rh_automation_hub]
+
           url=https://cloud.redhat.com/api/automation-hub/
+
           auth_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
+
           token=${{ secrets.ah_token }}
+
           EOF
+
           ansible-galaxy collection publish "${TARBALL}"
+
           rm ansible.cfg
