test consolidated release

diff --git a/.github/workflows/release_ah.yml b/.github/workflows/release_ah.yml
--- a/.github/workflows/release_ah.yml
+++ b/.github/workflows/release_ah.yml
@@ -22,22 +22,23 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - name: "Build the collection"
-        run: |
-          ansible-galaxy collection build -v --force
-
+      # - name: "Build the collection"
+      #   run: |
+      #     ansible-galaxy collection build -v --force
       - name: "Publish the collection on Automation Hub"
         if: ${{ inputs.ah_publish }} # failed automationhub job not prohibit galaxy job
         run: |
-          [[ "${{ secrets.ah_token != '' }}" ]] || { echo "ah_token is required to publish on automation hub" ; exit 1; }
-          TARBALL=$(ls -1 ./*.tar.gz)
-          cat << EOF > ansible.cfg
-          [galaxy]
-          server_list = rh_automation_hub
-          [galaxy_server.rh_automation_hub]
-          url=https://cloud.redhat.com/api/automation-hub/
-          auth_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
-          token=${{ secrets.ah_token }}
-          EOF
-          ansible-galaxy collection publish "${TARBALL}"
-          rm ansible.cfg
+          echo "${{ secrets.ah_token != '' }}"
+          echo "${{ secrets.ansible_galaxy_api_key != '' }}"
+        # [[ "${{ secrets.ah_token != '' }}" ]] || { echo "ah_token is required to publish on automation hub" ; exit 1; }
+        # TARBALL=$(ls -1 ./*.tar.gz)
+        # cat << EOF > ansible.cfg
+        # [galaxy]
+        # server_list = rh_automation_hub
+        # [galaxy_server.rh_automation_hub]
+        # url=https://cloud.redhat.com/api/automation-hub/
+        # auth_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
+        # token=${{ secrets.ah_token }}
+        # EOF
+        # ansible-galaxy collection publish "${TARBALL}"
+        # rm ansible.cfg
