add galaxy disable upload

diff --git a/.github/workflows/release_collection.yml b/.github/workflows/release_collection.yml
--- a/.github/workflows/release_collection.yml
+++ b/.github/workflows/release_collection.yml
@@ -35,7 +35,7 @@ jobs:
       - name: "Publish the collection on Automation Hub"
         if: ${{ inputs.ah_publish }}
         run: |
-          [[ "${{ secrets.ah_token != '' }}" ]] || { echo "ah_token is required to publish on automation hub" ; exit 1; }
+          [[ "${{ secrets.ah_token != '' }}" ]] || { echo "ah_token is required to publish on automation hub" ; exit 0; }
           TARBALL=$(ls -1 ./*.tar.gz)
           cat << EOF > ansible.cfg
           [galaxy]
@@ -43,10 +43,11 @@ jobs:
           [galaxy_server.rh_automation_hub]
           url=https://cloud.redhat.com/api/automation-hub/
           auth_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
-          token=${{ secrets.ah_token }}
-          EOF
-          ansible-galaxy collection publish "${TARBALL}"
           rm ansible.cfg
+
+        # token=${{ secrets.ah_token }}
+        # EOF
+        # ansible-galaxy collection publish "${TARBALL}"
 
   release_galaxy:
     runs-on: ubuntu-latest
@@ -62,6 +63,6 @@ jobs:
       - name: "Publish the collection on Galaxy"
         if: ${{ inputs.galaxy_publish }}
         run: |
-          [[ "${{ secrets.ansible_galaxy_api_key != '' }}" ]] || { echo "ansible_galaxy_api_key is required to publish on galaxy" ; exit 1; }
+          [[ "${{ secrets.ansible_galaxy_api_key != '' }}" ]] || { echo "ansible_galaxy_api_key is required to publish on galaxy" ; exit 0; }
           TARBALL=$(ls -1 ./*.tar.gz)
-          ansible-galaxy collection publish "${TARBALL}" --api-key "${{ secrets.ansible_galaxy_api_key }}"
+        # ansible-galaxy collection publish "${TARBALL}" --api-key "${{ secrets.ansible_galaxy_api_key }}"
